"""Added get_id method and ensured id column

Revision ID: 6d27a917cecd
Revises: 80e309545358
Create Date: 2025-04-28 19:22:56.752518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d27a917cecd'
down_revision = '80e309545358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_admin_email', ['email'])
        batch_op.create_unique_constraint('uq_admin_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint('uq_admin_username', type_='unique')
        batch_op.drop_constraint('uq_admin_email', type_='unique')

    # ### end Alembic commands ###
