"""added email verification

Revision ID: f9cda1f57552
Revises: e92b566f2220
Create Date: 2025-03-14 09:20:25.192871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9cda1f57552'
down_revision = 'e92b566f2220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_attendee')
    op.drop_table('meeting')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('your_column_name', existing_type=sa.String(), nullable=False)
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token')
        batch_op.drop_column('is_verified')

    op.create_table('meeting',
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('date_time', sa.DateTime(), nullable=True),
        sa.Column('location', sa.String(length=255), nullable=True),
        sa.Column('organizer_id', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['organizer_id'], ['employee.employee_id'], ),
        sa.PrimaryKeyConstraint('meeting_id')
    )
    
    op.create_table('meeting_attendee',
        sa.Column('attendee_id', sa.Integer(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=True),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employee.employee_id'], ),
        sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ),
        sa.PrimaryKeyConstraint('attendee_id')
    )
    # ### end Alembic commands ###
